default_install_hook_types:
  - pre-commit
repos:
  # Generates table of contents updates
  - repo: https://github.com/frnmst/md-toc
    rev: 9.0.0
    hooks:
      - id: md-toc
        files: ^README\.md$
